[upgrade] two now-broken npm dependencies
```
meteor npm i --save-dev @angular/compiler-cli@=7.2.15
meteor npm i --save @babel/runtime@=7.21.5
```

(Also, edit `package.json` to pinpoint dependencies to a precise version — Something I can't seem to do using the `meteor npm` command line.)

Required because
- `@angular/compiler-cli@7.1.1` used to depend on `chokidar@^1.4.2`, which depended on `fsevents@^1.0.0`, which we cannot build (because v8 API something something) nor download in binary form anymore (because it got withdrawn from the server it was at),
- `@babel/runtime@7.1.5` spewed `Error: Cannot find module '/Users/quatrava/Dev/angular-meteor/angular-meteor-base/.meteor/local/build/programs/server/node_modules/@babel/runtime/helpers/objectSpread2'` in a manner very similar to [this previous problem](https://forums.meteor.com/t/solved-cannot-find-module-babel-runtime-helpers-builtin-objectspread-after-update-meteor-to-1-6-1-1/43034/2) which was also cured by upgrading it.

Now both `meteor npm i` completes successfully (albeit with `npm audit` issues, some of them critical).